name: wedease
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.0
  get: ^4.6.5
  http: ^0.13.4
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2
  image_picker: ^1.0.0
  path: ^1.8.3
  intl: ^0.18.1
  url_launcher: ^6.1.14
  shake: ^2.2.0
  share_plus: ^7.1.0
  uuid: ^3.0.7
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - lib/services/category_model.json

fonts:
  - family: sans_regular
    fonts:
      - asset: fonts/sans_regular.ttf

  - family: sans_smilebold
    fonts:
      - asset: fonts/sans_smilebold.ttf

  - family: sans_bold
    fonts:
      - asset: fonts/sans_bold.ttf
